from django.urls import path
from . import bookViews,authorViews,memberLoanRequestViews,staffLoanRequestView, AccountView

urlpatterns=[
    path('',AccountView.homeRoleView,name='home-role'),
    path('staff_dashboard/',AccountView.staffDashboard,name='staff_dashboard'),
    path('member_dashboard/',AccountView.memberDashboard,name='member_dashboard'),
    path('admin_dashboard/',AccountView.adminDashboard,name='admin_dashboard'),
    path('authors/',authorViews.author_list,name='author_list'),
    path('authors/<int:author_id>',authorViews.author_details,name='author_details'),
    path('books/',bookViews.book_list,name='book_list'),
    path('books/<int:book_id>',bookViews.book_details,name='book_detail'),
    path('books/add',bookViews.AddBook,name="book_add"),
    path('books/update/<int:book_id>',bookViews.UpdateBook,name="book_update"),
    path('books/delete/<int:book_id>',bookViews.DeleteBook,name="book_delete"),
    path('books/<int:book_id>/<int:member_id>/loan/',bookViews.loanMgtView.as_view(),name='loanMgt'),
    path('books/<int:book_id>/loan/loan_request/',memberLoanRequestViews.LoanRequestView,name='loan_request'),
    path('loan_request/success/',memberLoanRequestViews.loan_request_success,name='loan_request_success'),
    path('notifications/',memberLoanRequestViews.recieveNotification,name='notifications'),
    path('notifications/<int:notification_id>/',memberLoanRequestViews.recieveNotification,name='recieveNotification'),
    path('notifications/<int:notification_id>/toggle/',memberLoanRequestViews.toggleNotificationRead,name='toggle_notification_read'),
    path('loan_request/list/',staffLoanRequestView.staffLoanRequestViewList,name='loan_request_list'),
    path('loan_request/<int:loan_request_id>/detail/',staffLoanRequestView.staffLoanRequestViewDetail,name='loan_request_detail'),
    path('loan_request/<int:loan_request_id>/approve/',staffLoanRequestView.staffLoanRequestViewApprove,name='loan_request_approve'),
    path('loan_request/<int:loan_request_id>/reject/',staffLoanRequestView.staffLoanRequestViewReject,name='loan_request_reject'),
    path('transactions/<int:transaction_id>/fine/',staffLoanRequestView.FineTransactionView,name='fine_transaction'),
    path('transactions/<int:transaction_id>/pay/',memberLoanRequestViews.PaymentView,name='pay_transaction'),
    path('transactions/success/', memberLoanRequestViews.fine_success, name='fine_success'),
    path('transactions/<int:transaction_id>/success/', memberLoanRequestViews.fine_success, name='fine_success_detail'),
    path('transactions/no_overdue/', memberLoanRequestViews.no_overdue, name='no_overdue'),
    path('api/loan_duration/', staffLoanRequestView.get_approved_loan_duration, name='api_loan_duration'),
    path('register/',AccountView.registerView,name='register'),
    path('login/',AccountView.loginView,name='login'),
    path('login/member/',AccountView.loginRoleView, {'role': 'member'}, name='login_member'),
    path('login/staff/',AccountView.loginRoleView, {'role': 'staff'}, name='login_staff'),
    path('login/admin/',AccountView.loginRoleView, {'role': 'admin'}, name='login_admin'),
    path('logout/',AccountView.logoutView,name='logout'),
]