# Generated by Django 6.0.2 on 2026-02-14 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='returned',
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(default='SHELF-01', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='max_loan_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACIVE', 'Active'), ('OVERDUE', 'Overdue'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(default='CS', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='dorm',
            field=models.CharField(default='Block-A', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='Student', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('loan_reqeust_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_duration', models.IntegerField()),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('pickup_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_book', to='lmsApp.book')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_loan', to='lmsApp.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_member', to='lmsApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lmsApp.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lmsApp.member')),
            ],
        ),
    ]
