# Generated by Django 6.0.2 on 2026-02-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_rename_loan_date_loan_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_loan', to='lmsApp.loan'),
        ),
    ]
