# Generated by Django 6.0.2 on 2026-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0004_loanrequest_pickup_limit_alter_loanrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20),
        ),
    ]
