# Generated by Django 6.0.2 on 2026-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_transaction_daily_rate_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('LOANED', 'Loaned'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
