# Generated by Django 6.0.2 on 2026-02-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_alter_loan_status_alter_loanrequest_status'),
    ]

    operations = []
