# Generated by Django 6.0.2 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0008_member_user_alter_user_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'status'], name='lmsApp_loan_member__bd114e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['book', 'status'], name='lmsApp_loan_book_id_c0c251_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date', 'status'], name='lmsApp_loan_due_dat_c89402_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'return_date'], name='lmsApp_loan_member__34ddc6_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['member', 'status'], name='lmsApp_loan_member__ded9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['book', 'status'], name='lmsApp_loan_book_id_686ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['status', 'created_at'], name='lmsApp_loan_status_b292ca_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['member', 'book', 'status'], name='lmsApp_loan_member__b1665c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['member', 'is_read'], name='lmsApp_noti_member__2a684b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['member', 'created_at'], name='lmsApp_noti_member__ebc9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['loan_request', 'created_at'], name='lmsApp_noti_loan_re_f8b73d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['member', 'status'], name='lmsApp_tran_member__d810d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['loan', 'status'], name='lmsApp_tran_loan_id_34c9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['member', 'created_at'], name='lmsApp_tran_member__ba8967_idx'),
        ),
    ]
